/**
 * @format
 */

// import '@react-native-async-storage/async-storage';
// import '@react-native-community/image-editor';
// import '@react-native-community/masked-view';
// import '@react-native-community/netinfo';
// import '@react-navigation/core';
// import '@react-navigation/drawer';
// import '@react-navigation/material-top-tabs';
// import '@react-navigation/native';
// import '@react-navigation/stack';
// import '@sentry/react-native';
// import '@smuxx/react-native-linkedin';
// import 'buffer';
// import 'dayjs';
// import 'diff';
// import 'emoji-mart-native';
// import 'he';
// import 'i18next';
// import 'lodash';
// import 'moment';
// import 'promise.allsettled';
// import 'react';
// import 'react-i18next';
// import 'react-native';
// import 'react-native-calendars';
// import 'react-native-camera';
// import 'react-native-config';
// import 'react-native-crypto-js';
// import 'react-native-date-picker';
// import 'react-native-device-info';
// import 'react-native-file-viewer';
// import 'react-native-flip-timer';
// import 'react-native-fs';
// import 'react-native-gesture-handler';
// import 'react-native-image-crop-picker';
// import 'react-native-jitsi-meet';
// import 'react-native-keyboard-aware-scroll-view';
// import 'react-native-linear-gradient';
// import 'react-native-permissions';
// import 'react-native-qrcode-scanner';
// import 'react-native-qrcode-svg';
// import 'react-native-ratings';
// import 'react-native-reanimated';
// import 'react-native-render-html';
// import 'react-native-safe-area-context';
// import 'react-native-screens';
// import 'react-native-share';
// import 'react-native-svg';
// import 'react-native-swiper-flatlist';
// import 'react-native-tab-view';
// import 'react-native-toast-message';
// import 'react-native-vector-icons';
// import 'react-native-view-shot';
// import 'react-native-webview';
// import 'react-native-youtube';
// import 'string.prototype.matchall';
// import 'styled-components';
// import 'xlsx';
import {AppRegistry} from 'react-native';
import App from './src/App';
import {name as appName} from './app.json';

AppRegistry.registerComponent(appName, () => App);
